/*
 * This file is generated by jOOQ.
 */
package org.xyplayman.demo.jooq;


import javax.annotation.processing.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;
import org.xyplayman.demo.jooq.tables.Article;
import org.xyplayman.demo.jooq.tables.ArticleTag;
import org.xyplayman.demo.jooq.tables.Tag;


/**
 * A class modelling indexes of tables of the <code>demo</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ARTICLE_PRIMARY = Indexes0.ARTICLE_PRIMARY;
    public static final Index ARTICLE_TAG_PRIMARY = Indexes0.ARTICLE_TAG_PRIMARY;
    public static final Index TAG_PRIMARY = Indexes0.TAG_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ARTICLE_PRIMARY = Internal.createIndex("PRIMARY", Article.ARTICLE, new OrderField[] { Article.ARTICLE.ID }, true);
        public static Index ARTICLE_TAG_PRIMARY = Internal.createIndex("PRIMARY", ArticleTag.ARTICLE_TAG, new OrderField[] { ArticleTag.ARTICLE_TAG.ARTICLE_ID, ArticleTag.ARTICLE_TAG.TAG_ID }, true);
        public static Index TAG_PRIMARY = Internal.createIndex("PRIMARY", Tag.TAG, new OrderField[] { Tag.TAG.ID }, true);
    }
}
