/*
 * This file is generated by jOOQ.
 */
package org.xyplayman.demo.jooq;


import javax.annotation.processing.Generated;

import org.xyplayman.demo.jooq.tables.Article;
import org.xyplayman.demo.jooq.tables.ArticleTag;
import org.xyplayman.demo.jooq.tables.Tag;


/**
 * Convenience access to all tables in demo
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 文章
     */
    public static final Article ARTICLE = Article.ARTICLE;

    /**
     * 文章和标签关联
     */
    public static final ArticleTag ARTICLE_TAG = ArticleTag.ARTICLE_TAG;

    /**
     * 标签
     */
    public static final Tag TAG = Tag.TAG;
}
